name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Updated to the latest version
    - name: Set up Python
      uses: actions/setup-python@v5  # Updated to the latest version
      with:
        python-version: '3.8'  # Specify the exact Python version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt  # Ensure Bandit is listed in requirements.txt
    - name: Run Bandit security scan
      run: |
        bandit -r .